# Generated by Django 4.2.16 on 2026-07-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('PKWT', 'PKWT (Karyawan Kontrak)'), ('PKWTT', 'PKWTT (Karyawan Tetap)'), ('BHL', 'BHL (Buruh Harian Lepas)')], max_length=5, verbose_name='Jenis Kontrak')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan untuk PKWTT (karyawan tetap)', null=True, verbose_name='Tanggal Selesai')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gaji Pokok')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/documents/', verbose_name='Dokumen Kontrak (PDF)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Diakhiri'), ('RENEWED', 'Diperbarui')], default='ACTIVE', max_length=12, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_end_date', models.DateField(verbose_name='Tanggal Berakhir Baru')),
                ('new_salary_base', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan jika tidak ada perubahan gaji', max_digits=15, null=True, verbose_name='Gaji Pokok Baru')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/renewals/', verbose_name='Dokumen Pembaruan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('original_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.contract', verbose_name='Kontrak Asal')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Contract Renewal',
                'verbose_name_plural': 'Contract Renewals',
                'ordering': ['-renewed_at'],
            },
        ),
    ]
