# Generated by Django 4.2.16 on 2026-08-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_entity_alter_employee_nik_and_more'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee', verbose_name='Karyawan'),
        ),
        migrations.AlterField(
            model_name='contractrenewal',
            name='original_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='contracts.contract', verbose_name='Kontrak Asal'),
        ),
    ]
