# Generated by Django 4.2.16 on 2026-07-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Asesmen / Kuis')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Nilai Kelulusan (%)')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='0 = Tanpa batas waktu', verbose_name='Batas Waktu (Menit)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Wajib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Teks Pertanyaan')),
                ('question_type', models.CharField(choices=[('MCQ', 'Pilihan Ganda'), ('TRUE_FALSE', 'Benar / Salah'), ('ESSAY', 'Essay')], default='MCQ', max_length=15, verbose_name='Tipe Soal')),
                ('points', models.PositiveSmallIntegerField(default=10, verbose_name='Bobot / Poin')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Urutan Soal')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assessment', verbose_name='Asesmen')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Teks Opsi Jawaban')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kunci Jawaban')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessment.question', verbose_name='Pertanyaan')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Mulai')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Skor (%)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Lulus')),
                ('answers', models.JSONField(default=dict, verbose_name='Detail Jawaban Karyawan')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessment', verbose_name='Asesmen')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
