# Generated by Django 4.2.16 on 2026-07-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Asesmen / Kuiz')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Nilai Kelulusan (Passing Score)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Assessment Template',
                'verbose_name_plural': 'Assessment Templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Pertanyaan')),
                ('options', models.JSONField(default=list, help_text='JSON List of choices: [{"key": "A", "text": "Opt A"}, ...]', verbose_name='Pilihan Jawaban')),
                ('correct_answer', models.CharField(help_text='Misal: A, B, atau teks jawaban', max_length=50, verbose_name='Kunci Jawaban')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Bobot Soal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assessmenttemplate', verbose_name='Template Asesmen')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='Jawaban Karyawan')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Skor')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Lulus')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='employees.employee', verbose_name='Karyawan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assessmenttemplate', verbose_name='Template Asesmen')),
            ],
            options={
                'verbose_name': 'Assessment Submission',
                'verbose_name_plural': 'Assessment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
