# Generated by Django 4.2.16 on 2026-07-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('company', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='training.trainingparticipant', verbose_name='Peserta Pelatihan'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='company.entity', verbose_name='Entitas'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.trainingprogram', verbose_name='Program Pelatihan'),
        ),
    ]
