# Generated by Django 4.2.16 on 2026-07-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_categories', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Training Category',
                'verbose_name_plural': 'Training Categories',
                'ordering': ['name'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pelatihan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('objectives', models.TextField(blank=True, verbose_name='Tujuan Pelatihan')),
                ('trainer', models.CharField(max_length=150, verbose_name='Pelatih / Instruktur')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0 = Tidak terbatas', verbose_name='Maksimal Peserta')),
                ('material', models.FileField(blank=True, null=True, upload_to='training/materials/', verbose_name='Modul / Materi (PDF)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Pendaftaran Dibuka'), ('ONGOING', 'Berlangsung'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Batal')], default='DRAFT', max_length=15, verbose_name='Status Pelatihan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='training.trainingcategory', verbose_name='Kategori Pelatihan')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Terdaftar'), ('PASSED', 'Lulus'), ('FAILED', 'Tidak Lulus'), ('CANCELLED', 'Batal')], default='REGISTERED', max_length=15, verbose_name='Status Kelulusan')),
                ('attendance', models.CharField(choices=[('REGISTERED', 'Terdaftar'), ('ATTENDED', 'Hadir'), ('ABSENT', 'Tidak Hadir'), ('CANCELLED', 'Batal')], default='REGISTERED', max_length=15, verbose_name='Kehadiran')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai / Skor')),
                ('kpi_snapshot', models.JSONField(blank=True, help_text='Snapshot KPI aktif karyawan saat didaftarkan ke pelatihan', null=True, verbose_name='KPI Pre-Training Snapshot')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training/certificates/', verbose_name='Sertifikat')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Evaluasi')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pendaftaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participations', to='employees.employee', verbose_name='Karyawan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.trainingprogram', verbose_name='Program Pelatihan')),
            ],
            options={
                'verbose_name': 'Training Participant',
                'verbose_name_plural': 'Training Participants',
                'unique_together': {('program', 'employee')},
            },
        ),
    ]
