# Generated by Django 4.2.16 on 2026-07-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pelatihan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('trainer', models.CharField(max_length=150, verbose_name='Pelatih / Instruktur')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lokasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Terdaftar'), ('PASSED', 'Lulus'), ('FAILED', 'Tidak Lulus'), ('CANCELLED', 'Batal')], default='REGISTERED', max_length=15, verbose_name='Status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai / Skor')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training/certificates/', verbose_name='Sertifikat')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Evaluasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participations', to='employees.employee', verbose_name='Karyawan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.trainingprogram', verbose_name='Program Pelatihan')),
            ],
            options={
                'verbose_name': 'Training Participant',
                'verbose_name_plural': 'Training Participants',
                'unique_together': {('program', 'employee')},
            },
        ),
    ]
