# Generated by Django 4.2.16 on 2026-07-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPIAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Tahun Periode')),
                ('period_index', models.PositiveSmallIntegerField(default=1, help_text='Bulan (1-12) atau Triwulan (1-4) atau 1 (Tahunan)', verbose_name='Indeks Periode')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui Manager'), ('FINAL', 'Final (Evaluasi Selesai)')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai KPI Akhir (%)')),
                ('evaluator_notes', models.TextField(blank=True, verbose_name='Catatan Evaluator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Employee KPI Assignment',
                'verbose_name_plural': 'Employee KPI Assignments',
            },
        ),
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Template KPI')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Bulanan'), ('QUARTERLY', 'Triwulan (3 Bulan)'), ('ANNUAL', 'Tahunan')], default='MONTHLY', max_length=10, verbose_name='Tipe Periode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_templates', to='employees.department', verbose_name='Departemen')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_templates', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'KPI Template',
                'verbose_name_plural': 'KPI Templates',
            },
        ),
        migrations.CreateModel(
            name='KPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255, verbose_name='Indikator Kinerja')),
                ('target', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target')),
                ('unit', models.CharField(max_length=50, verbose_name='Satuan (misal: %, Transaksi, Jam)')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Total bobot dalam 1 template idealnya 100%', max_digits=5, verbose_name='Bobot (%)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kpi.kpitemplate', verbose_name='Template KPI')),
            ],
            options={
                'verbose_name': 'KPI Item',
                'verbose_name_plural': 'KPI Items',
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPIResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_achievement', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capaian Aktual')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor Terbobot (%)')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpi.employeekpiassignment', verbose_name='Penugasan KPI')),
                ('kpi_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpiitem', verbose_name='Indikator KPI')),
            ],
            options={
                'verbose_name': 'Employee KPI Result Item',
                'verbose_name_plural': 'Employee KPI Result Items',
            },
        ),
        migrations.AddField(
            model_name='employeekpiassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpi.kpitemplate', verbose_name='Template KPI'),
        ),
        migrations.AlterUniqueTogether(
            name='employeekpiassignment',
            unique_together={('employee', 'template', 'period_year', 'period_index')},
        ),
    ]
