# Generated by Django 4.2.16 on 2026-07-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekpiassignment',
            name='related_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_kpis', to='training.trainingprogram', verbose_name='Pelatihan Terkait'),
        ),
        migrations.AddField(
            model_name='employeekpiassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpi.kpitemplate', verbose_name='Template KPI'),
        ),
    ]
