# Generated by Django 4.2.16 on 2026-07-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Perusahaan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('npwp', models.CharField(blank=True, max_length=30, verbose_name='NPWP')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Entitas')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Entitas')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('npwp', models.CharField(blank=True, max_length=30, verbose_name='NPWP')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('payroll_cutoff_day', models.PositiveSmallIntegerField(default=25, help_text='Tanggal tutup buku penggajian setiap bulan (1-31)', verbose_name='Tanggal Cutoff Payroll')),
                ('leave_approval_levels', models.PositiveSmallIntegerField(default=2, help_text='Jumlah level approver untuk cuti (1 = direct manager only)', verbose_name='Jumlah Level Approval Cuti')),
                ('employee_id_format', models.CharField(default='{ENTITY_CODE}-{YEAR}-{SEQ}', max_length=50, verbose_name='Format ID Karyawan')),
                ('employee_id_seq_padding', models.PositiveSmallIntegerField(default=4, help_text='Jumlah digit untuk nomor urut (4 = 0001)', verbose_name='Padding Nomor Urut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='company.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
    ]
