# Generated by Django 4.2.16 on 2026-08-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='employee_id_last_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
