# Generated by Django 4.2.16 on 2026-07-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jenis Cuti')),
                ('max_days_per_year', models.PositiveSmallIntegerField(verbose_name='Maks. Hari per Tahun')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Cuti Berbayar')),
                ('applicable_to', models.CharField(choices=[('PKWT', 'PKWT'), ('PKWTT', 'PKWTT'), ('ALL', 'Semua (PKWT & PKWTT)')], default='ALL', help_text='BHL dikecualikan dari sistem cuti', max_length=5, verbose_name='Berlaku untuk')),
                ('allow_halfday', models.BooleanField(default=False, verbose_name='Boleh Setengah Hari')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='Wajib Lampiran')),
                ('carry_forward_days', models.PositiveSmallIntegerField(default=0, verbose_name='Maks. Carry Forward (hari)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Jumlah Hari')),
                ('is_halfday', models.BooleanField(default=False, verbose_name='Setengah Hari')),
                ('reason', models.TextField(verbose_name='Alasan Cuti')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave/attachments/', verbose_name='Lampiran')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pengajuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Karyawan')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leave.leavetype', verbose_name='Jenis Cuti')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('allocated', models.PositiveSmallIntegerField(default=0, verbose_name='Alokasi (hari)')),
                ('used', models.PositiveSmallIntegerField(default=0, verbose_name='Terpakai (hari)')),
                ('carry_forward', models.PositiveSmallIntegerField(default=0, verbose_name='Carry Forward (hari)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Karyawan')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype', verbose_name='Jenis Cuti')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text="1 = Direct Manager, 2 = Manager's Manager, dst.", verbose_name='Level Approval')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=8, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Approver')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Keputusan')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to='employees.employee', verbose_name='Approver')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest', verbose_name='Permohonan Cuti')),
            ],
            options={
                'verbose_name': 'Leave Approval',
                'verbose_name_plural': 'Leave Approvals',
                'ordering': ['level'],
                'unique_together': {('leave_request', 'level')},
            },
        ),
    ]
