# Generated by Django 4.2.16 on 2026-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaveapproval_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='allocated',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Alokasi (hari)'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='carry_forward',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Carry Forward (hari)'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Terpakai (hari)'),
        ),
    ]
