# Generated by Django 4.2.16 on 2026-07-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=8, verbose_name='Skema PPh21')),
                ('ptkp_status', models.CharField(max_length=5, verbose_name='Status PTKP')),
                ('ptkp_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nilai PTKP')),
                ('gross_annual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Penghasilan Bruto Setahun')),
                ('biaya_jabatan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Biaya Jabatan')),
                ('pkp_annual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PKP Setahun')),
                ('tax_annual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PPh21 Setahun')),
                ('tax_monthly', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PPh21 per Bulan')),
                ('detail', models.JSONField(default=dict, verbose_name='Detail Perhitungan')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_log', to='payroll.payrollitem', verbose_name='Payroll Item')),
            ],
            options={
                'verbose_name': 'Tax Calculation Log',
                'verbose_name_plural': 'Tax Calculation Logs',
            },
        ),
        migrations.CreateModel(
            name='PTKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun Pajak')),
                ('status_code', models.CharField(help_text='TK/0, TK/1, K/0, K/1, K/2, K/3', max_length=5, verbose_name='Kode Status PTKP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nilai PTKP')),
            ],
            options={
                'verbose_name': 'PTKP',
                'verbose_name_plural': 'PTKP',
                'ordering': ['year', 'status_code'],
                'unique_together': {('year', 'status_code')},
            },
        ),
        migrations.CreateModel(
            name='PPh21Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun Pajak')),
                ('income_from', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PKP Dari (Rp)')),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan untuk bracket terakhir (> X)', max_digits=20, null=True, verbose_name='PKP Sampai (Rp)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarif (%)')),
            ],
            options={
                'verbose_name': 'PPh21 Bracket',
                'verbose_name_plural': 'PPh21 Brackets',
                'ordering': ['year', 'income_from'],
                'unique_together': {('year', 'income_from')},
            },
        ),
    ]
