# Generated by Django 4.2.16 on 2026-08-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_overtimerecord_employee_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculationlog',
            name='payroll_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_log', to='payroll.payrollitem', verbose_name='Payroll Item'),
        ),
        migrations.CreateModel(
            name='PPh21TERRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun Pajak')),
                ('category', models.CharField(choices=[('A', 'Kategori A'), ('B', 'Kategori B'), ('C', 'Kategori C')], max_length=1, verbose_name='Kategori TER')),
                ('income_from', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Bruto Dari (Rp)')),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan untuk bracket tertinggi', max_digits=20, null=True, verbose_name='Bruto Sampai (Rp)')),
                ('rate_percent', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tarif (%)')),
            ],
            options={
                'verbose_name': 'PPh21 TER Rate',
                'verbose_name_plural': 'PPh21 TER Rates',
                'ordering': ['year', 'category', 'income_from'],
                'unique_together': {('year', 'category', 'income_from')},
            },
        ),
    ]
