# Generated by Django 4.2.16 on 2026-07-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Shift')),
                ('work_start', models.TimeField(verbose_name='Jam Mulai Kerja')),
                ('work_end', models.TimeField(verbose_name='Jam Selesai Kerja')),
                ('break_duration', models.PositiveSmallIntegerField(default=60, verbose_name='Durasi Istirahat (menit)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Berlaku Mulai')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee', verbose_name='Karyawan')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='attendance.workschedule', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedules',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('source', models.CharField(choices=[('FINGER', 'Mesin Finger'), ('MANUAL', 'Manual (HR)'), ('SYSTEM', 'System')], default='FINGER', max_length=6, verbose_name='Sumber Data')),
                ('late_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Keterlambatan (menit)')),
                ('early_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Pulang Awal (menit)')),
                ('work_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Durasi Kerja (menit)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('raw_data', models.JSONField(blank=True, help_text='Data mentah dari mesin finger / sumber eksternal', null=True, verbose_name='Raw Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
