# Generated by Django 4.2.16 on 2026-08-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_entity_alter_employee_nik_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='employees.employee', verbose_name='Karyawan'),
        ),
    ]
