# Generated by Django 4.2.16 on 2026-07-26 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Komponen')),
                ('component_type', models.CharField(choices=[('EARNING', 'Penghasilan'), ('DEDUCTION', 'Potongan')], max_length=9, verbose_name='Tipe')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Kena Pajak')),
                ('is_fixed', models.BooleanField(default=True, verbose_name='Tetap (bukan variabel)')),
                ('formula_type', models.CharField(choices=[('FIXED', 'Nominal Tetap'), ('PCT_BASIC', '% dari Gaji Pokok'), ('CUSTOM', 'Formula Kustom')], default='FIXED', max_length=9, verbose_name='Tipe Formula')),
                ('formula_value', models.DecimalField(decimal_places=4, default=0, help_text='Nominal (FIXED) atau persentase (PCT_BASIC, mis. 10 = 10%)', max_digits=10, verbose_name='Nilai Formula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['component_type', 'name'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Bulan')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Sedang Diproses'), ('FINALIZED', 'Final'), ('PAID', 'Sudah Dibayar')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Finalisasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('entity', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal Lembur')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Jam Lembur')),
                ('overtime_type', models.CharField(choices=[('WEEKDAY', 'Hari Kerja'), ('WEEKEND', 'Hari Libur/Akhir Pekan'), ('HOLIDAY', 'Hari Nasional')], default='WEEKDAY', max_length=7, verbose_name='Tipe Lembur')),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Multiplier Tarif')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nominal Lembur (calculated)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='employees.employee', verbose_name='Karyawan')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='payroll.payrollperiod', verbose_name='Periode Payroll')),
            ],
            options={
                'verbose_name': 'Overtime Record',
                'verbose_name_plural': 'Overtime Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pph21_scheme', models.CharField(choices=[('GROSS', 'Gross (dipotong dari gaji)'), ('GROSS_UP', 'Gross Up (ditanggung perusahaan)'), ('NET', 'Net (tidak direfleksikan)')], default='GROSS', max_length=8, verbose_name='Skema PPh21')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bpjs_kes_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_kes_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jkk_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jkm_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jht_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jht_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jp_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bpjs_jp_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pph21_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('breakdown', models.JSONField(default=dict, help_text='Detail lengkap semua komponen gaji', verbose_name='Breakdown Komponen')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='employees.employee', verbose_name='Karyawan')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollperiod', verbose_name='Periode')),
            ],
            options={
                'verbose_name': 'Payroll Item',
                'verbose_name_plural': 'Payroll Items',
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Override nominal komponen untuk karyawan ini', max_digits=15, verbose_name='Nominal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Berlaku Mulai')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='payroll.salarycomponent', verbose_name='Komponen')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Employee Salary Component',
                'verbose_name_plural': 'Employee Salary Components',
                'unique_together': {('employee', 'component')},
            },
        ),
    ]
