# Generated by Django 4.2.16 on 2026-07-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kode Departemen')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
                ('grade_level', models.PositiveSmallIntegerField(default=1, help_text='Semakin tinggi angka, semakin tinggi jabatan', verbose_name='Level Grade')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name='Departemen')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Auto-generated: HO-2024-0001', max_length=30, unique=True, verbose_name='ID Karyawan')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK KTP')),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('date_of_birth', models.DateField(verbose_name='Tanggal Lahir')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('religion', models.CharField(blank=True, max_length=50, verbose_name='Agama')),
                ('blood_type', models.CharField(blank=True, max_length=3, verbose_name='Golongan Darah')),
                ('marital_status', models.CharField(choices=[('TK', 'Tidak Kawin'), ('K', 'Kawin'), ('D', 'Cerai')], default='TK', max_length=2, verbose_name='Status Pernikahan')),
                ('dependants', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Tanggungan')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Kontak Darurat')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Foto')),
                ('join_date', models.DateField(verbose_name='Tanggal Bergabung')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Keluar')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Tidak Aktif'), ('TERMINATED', 'PHK / Keluar')], default='ACTIVE', max_length=15, verbose_name='Status Karyawan')),
                ('npwp', models.CharField(blank=True, max_length=25, verbose_name='NPWP')),
                ('ptkp_status', models.CharField(choices=[('TK/0', 'TK/0 - Tidak Kawin, 0 Tanggungan'), ('TK/1', 'TK/1 - Tidak Kawin, 1 Tanggungan'), ('TK/2', 'TK/2 - Tidak Kawin, 2 Tanggungan'), ('TK/3', 'TK/3 - Tidak Kawin, 3 Tanggungan'), ('K/0', 'K/0  - Kawin, 0 Tanggungan'), ('K/1', 'K/1  - Kawin, 1 Tanggungan'), ('K/2', 'K/2  - Kawin, 2 Tanggungan'), ('K/3', 'K/3  - Kawin, 3 Tanggungan')], default='TK/0', max_length=5, verbose_name='Status PTKP')),
                ('bpjs_kes_no', models.CharField(blank=True, max_length=30, verbose_name='No. BPJS Kesehatan')),
                ('bpjs_tk_no', models.CharField(blank=True, max_length=30, verbose_name='No. BPJS Ketenagakerjaan')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='Nama Bank')),
                ('bank_account_no', models.CharField(blank=True, max_length=30, verbose_name='No. Rekening')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Pemilik Rekening')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Departemen')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.entity', verbose_name='Entitas')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Manager / Atasan')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Jabatan')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee', verbose_name='Kepala Departemen'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'name')},
        ),
    ]
