# Generated by Django 4.2.16 on 2026-07-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pph21_scheme',
            field=models.CharField(choices=[('GROSS', 'Gross (dipotong dari gaji)'), ('GROSS_UP', 'Gross Up (ditanggung perusahaan)'), ('NET', 'Net (tidak direfleksikan)')], default='GROSS', help_text='Skema pemotongan PPh21 yang ditanggung karyawan ini', max_length=8, verbose_name='Skema PPh21'),
        ),
    ]
