# Generated by Django 4.2.16 on 2026-08-02 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_entity_employee_id_last_sequence'),
        ('employees', '0003_employee_add_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='company.entity', verbose_name='Entitas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'NIK harus 16 digit angka')], verbose_name='NIK KTP'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='employees.department', verbose_name='Departemen'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'department', 'entity'], name='employees_e_status_753e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['entity'], name='employees_e_entity__cf2fe3_idx'),
        ),
    ]
