# Generated by Django 4.2.16 on 2026-07-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=100, verbose_name='Nama Penandatangan')),
                ('signer_position', models.CharField(max_length=100, verbose_name='Jabatan Penandatangan')),
                ('signature_image', models.ImageField(upload_to='salary_slip/signatures/', verbose_name='Gambar Tanda Tangan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_config', to='company.entity', verbose_name='Entitas')),
            ],
            options={
                'verbose_name': 'Signature Config',
                'verbose_name_plural': 'Signature Configs',
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(help_text='Format: SLIP-HO-2024-06-0001', max_length=50, unique=True, verbose_name='Nomor Slip')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='salary_slip/pdfs/', verbose_name='File PDF')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Sudah Ditandatangani')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Generate')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sudah Dikirim')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dikirim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slip', to='payroll.payrollitem', verbose_name='Payroll Item')),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'ordering': ['-created_at'],
            },
        ),
    ]
