# Generated by Django 4.2.16 on 2026-08-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_overtimerecord_employee_and_more'),
        ('salary_slip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='payroll_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary_slip', to='payroll.payrollitem', verbose_name='Payroll Item'),
        ),
    ]
