# Generated by Django 4.2.16 on 2026-07-26 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('notification_type', models.CharField(choices=[('CONTRACT_EXPIRING', 'Kontrak Mau Habis'), ('LEAVE_APPROVAL', 'Persetujuan Cuti'), ('PAYROLL_READY', 'Slip Gaji Tersedia'), ('SYSTEM', 'Sistem')], default='SYSTEM', max_length=25, verbose_name='Tipe')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Penerima')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
